version: "3.9"
   
services:
  db:
    container_name: "simulator_mysql"
    image:  mysql:8.0.21
    ports:
    - "3307:3306"
    environment:
      MYSQL_DATABASE: 'twitter_env'
      MYSQL_ROOT_USER: 'root'
      MYSQL_PASSWORD: '123456789'
      MYSQL_ROOT_PASSWORD: '123456789'
    
    volumes:
     - mysql-data:/var/lib/mysql
 
    restart: always
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
   
  web:
    container_name: "simulator_django"
    image: django
    build: ./Simulator
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql-data:
      