# Generated by Django 3.2.8 on 2021-11-21 00:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='durationParticipation',
        ),
        migrations.AddField(
            model_name='participant',
            name='beginTime',
            field=models.TimeField(default=datetime.datetime(2021, 11, 21, 0, 26, 10, 436957, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='participant',
            name='endTime',
            field=models.TimeField(default=datetime.datetime(2021, 11, 21, 0, 26, 10, 436957, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='hashtag',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='replyContent',
            field=models.CharField(default=' ', max_length=280),
        ),
        migrations.AlterField(
            model_name='participant',
            name='personality',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
