# Generated by Django 3.2.8 on 2021-11-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='Configuration',
            new_name='configuration',
        ),
    ]
