# Generated by Django 3.2.8 on 2021-11-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20211121_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='beginTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='endTime',
            field=models.TimeField(),
        ),
    ]
