# Generated by Django 3.2.8 on 2021-11-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_rename_configuration_interaction_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(default=' ', max_length=50, null=True),
        ),
    ]
