# Generated by Django 3.2.8 on 2021-11-24 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20211121_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configName', models.CharField(max_length=10)),
                ('space_for_comment', models.BooleanField(default=0)),
                ('user_picture', models.BooleanField(default=0)),
                ('reply_button', models.BooleanField(default=0)),
                ('like_button', models.BooleanField(default=0)),
                ('share_button', models.BooleanField(default=0)),
                ('block_button', models.BooleanField(default=0)),
                ('follow_button', models.BooleanField(default=0)),
                ('retweet_button', models.BooleanField(default=0)),
                ('posts_number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.configuration')),
            ],
        ),
    ]
