# Generated by Django 3.2.8 on 2021-11-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_configuration_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='lower_limit_interaction',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='configuration',
            name='uper_limit_interaction',
            field=models.IntegerField(default=1),
        ),
    ]
