# Generated by Django 3.2.8 on 2021-12-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='space_for_creat_post',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='Post_by_participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=280)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.configuration')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.participant')),
            ],
        ),
    ]
